---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: fill
---


```{r setup, include=FALSE}

rm(list=ls(all.names=TRUE))

#------------------ Packages ------------------
library(flexdashboard)
library(coronavirus)
data(coronavirus)
library(dplyr)
library(tidyr)
library(plotly)
library(DT)


#------------------ Parameters ------------------
# Set colors
# https://www.w3.org/TR/css-color-3/#svg-color
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"

#------------------ Data ------------------




coronavirus <- coronavirus %>% 
  ungroup() %>%
  mutate(country = if_else(Country.Region=="United Arab Emirates","UAE",Country.Region)) %>%
  mutate(country = if_else(country=="Mainland China", "China", country)) %>%
  mutate(country = if_else(country=="North Macedonia", "N.Macedonia", country)) %>%
  mutate(country = trimws(country)) %>%
  mutate(country = factor(country))



#Pivot by Country (Rami Krispin)
df <- coronavirus %>% 
  group_by(Country.Region, country, type) %>%
  summarise(total = sum(cases)) %>%
  pivot_wider(names_from =  type, values_from = total, values_fill = list(total=0))  %>%
  mutate(active = confirmed - recovered - death) %>%
  mutate(recover_rate = recovered / confirmed, death_rate = death / confirmed, active_rate = active / confirmed) %>% 
  arrange(-confirmed) %>%
  ungroup()
  
  
  

#Pivot by Country & Date
df1 <- coronavirus %>% 
  group_by(Country.Region, Lat , Long , country, Province.State, date, type) %>%
  summarise(total = sum(cases)) %>%
  pivot_wider(names_from= type, values_from = total, values_fill = list(total=0)) %>%
  mutate(active = confirmed - recovered - death)



df_iran <- df[df$Country.Region=='Iran',]



#Trend (Rami Krispin)
df_daily <- coronavirus %>% 
  group_by(date, type) %>%
  summarise(total = sum(cases, na.rm = TRUE)) %>%
  pivot_wider(names_from = type, values_from = total, values_fill = list(total=0)) %>%
  arrange(date) %>%
  ungroup() %>%
  mutate(active =  confirmed - recovered - death) %>%
  mutate(confirmed_cum = cumsum(confirmed),
         death_cum = cumsum(death),
         recovered_cum = cumsum(recovered),
         active_cum = cumsum(active))


  

trend_iran <- coronavirus %>% 
  filter(Country.Region == 'Iran') %>%
  group_by(date, type) %>%
  summarise(total = sum(cases, na.rm = TRUE)) %>%
  pivot_wider(names_from = type, values_from = total, values_fill = list(total=0)) %>%
  arrange(date) %>%
  ungroup() %>%
  mutate(active =  confirmed - recovered - death) %>%
  mutate(confirmed_cum = cumsum(confirmed),
         death_cum = cumsum(death),
         recovered_cum = cumsum(recovered),
         active_cum = cumsum(active))




max_date <- coronavirus %>% 
  filter(date == max(date)) %>%
  select(Country.Region,country, type, cases) %>%
  group_by(country, type) %>%
  summarise(total = sum(cases)) %>%
  pivot_wider(names_from = type, values_from = total, values_fill = list(total=0)) %>%
  arrange(-confirmed)



min_date <- coronavirus %>%
  group_by(Country.Region) %>%
  summarise(min_date = min(date)) %>%
  arrange(min_date)







```

WORLD
=======================================================================

Row
-----------------------------------------------------------------------
  
### confirmed {.value-box}
  
```{r}

valueBox(value = paste(format(sum(df$confirmed), big.mark = ","), "", sep = " "), 
         caption = "Total Confirmed Cases", 
         icon = "fas fa-user-md", 
         color = confirmed_color)
```


### active {.value-box}

```{r}
valueBox(value = paste(format(sum(df$active), big.mark = ",")
                       ," ("
                       ,round(100 * sum(df$active) / sum(df$confirmed), 1)
                       ,"%)"
                       ,sep = ""), 
         caption = "Active Cases", icon = "fas fa-ambulance", 
         color = active_color)
```

### recovered {.value-box}

```{r}
valueBox(value = paste(format(sum(df$recovered), big.mark = ",")
                       ," ("
                       ,round(100 * sum(df$recovered) / sum(df$confirmed), 1) 
                       ,"%)"
                       ,sep = ""), 
         caption = "Recovered Cases", icon = "fas fa-heartbeat", 
         color = recovered_color)
```

### death {.value-box}

```{r}

valueBox(value = paste(format(sum(df$death), big.mark = ",")
                       ," ("
                       ,round(100 * sum(df$death) / sum(df$confirmed), 1)
                       ,"%)"
                       ,sep = ""),
         caption = "Death Cases", 
         icon = "fas fa-heart-broken", 
         color = death_color)
```


